=== noi-techpark/odh-alpinebits-destination-data-server/src/schemas/agent.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://www.alpinebits.org/destinationdata/schemas/2022-04/agent",
  "description": "A resource that implements the concept of Agent defined in the AlpineBitsÂ® DestinationData Ontology.",
  "type": "object",
  "additionalProperties": false,
  "required": [ "type" ],
  "properties": {
    "id": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/id"
    },
    "type": {
      "const": "agents"
    },
    "meta": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/meta"
    },
    "links": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/links"
    },
    "attributes": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "abstract": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "contactPoints": {
          "type": [ "null", "array" ],
          "items": {
            "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/contactPoint"
          },
          "minItems": 1
        },
        "description": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "name": {
          "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
        },
        "shortName": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "url": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/complexUrl"
            }
          ]
        }
      }
    },
    "relationships": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "categories": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToMany"
            }
          ]
        },
        "multimediaDescriptions": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToMany"
            }
          ]
        }
      }
    }
  }
}

=== noi-techpark/odh-alpinebits-destination-data-server/test/model/odh2destinationdata/sample_publisher_output.json
{
  "type": "agents",
  "id": "CDB3CC1EE2614488A451C467BE971571_publisher",
  "meta": {
    "dataProvider": "http://tourism.opendatahub.com/",
    "lastUpdate": "2019-11-05T00:05:58.776531+01:00"
  },
  "links": {
    "self": "http://example.com/2021-04/agents/CDB3CC1EE2614488A451C467BE971571_publisher"
  },
  "attributes": {
    "abstract": null,
    "description": null,
    "name": {
      "deu": "LTS - Landesverband der Tourismusorganisationen Südtirols",
      "eng": "LTS - Landesverband der Tourismusorganisationen Südtirols",
      "ita": "LTS - Landesverband der Tourismusorganisationen Südtirols"
    },
    "shortName": null,
    "url": "https://lts.it",
    "contactPoints": null
  },
  "relationships": {
    "categories": null,
    "multimediaDescriptions": null
  }
}

=== noi-techpark/odh-alpinebits-destination-data-server/test/model/odh2destinationdata/sample_organizer_output.json
{
  "type": "agents",
  "id": "CDB3CC1EE2614488A451C467BE971571_organizer",
  "meta": {
    "dataProvider": "http://tourism.opendatahub.bz.it/",
    "lastUpdate": "2019-11-05T00:05:58.776531+01:00"
  },
  "links": {
    "self": "http://example.com/2021-04/agents/CDB3CC1EE2614488A451C467BE971571_organizer"
  },
  "attributes": {
    "abstract": null,
    "description": null,
    "name": {
      "deu": "LTS - Landesverband der Tourismusorganisationen Südtirols",
      "eng": "LTS - Landesverband der Tourismusorganisationen Südtirols",
      "ita": "LTS - Landesverband der Tourismusorganisationen Südtirols"
    },
    "shortName": null,
    "url": {
      "deu": "http://www.feldthurns.info",
      "eng": "http://www.feldthurns.info",
      "ita": "http://www.feldthurns.info"
    },
    "contactPoints": [
      {
        "address": {
          "street": {
            "deu": "Marktplatz 1",
            "eng": ".",
            "ita": "Piazza Mercato 1"
          },
          "city": {
            "deu": "Klausen",
            "eng": ".",
            "ita": "Chiusa"
          },
          "region": null,
          "complement": null,
          "categories": null,
          "zipcode": null,
          "zipCode": "39040"
        },
        "availableHours": null,
        "email": "info@feldthurns.info",
        "telephone": "+390472855290"
      }
    ]
  },
  "relationships": {
    "categories": null,
    "multimediaDescriptions": null
  }
}

=== noi-techpark/odh-alpinebits-destination-data-server/test/model/odh2destinationdata/sample_copyright_owner_output.json
{
  "type": "agents",
  "id": "bc59f5dd810efdceb1fc673567d02a2f_copyrightOwner",
  "meta": {
    "dataProvider": "http://tourism.opendatahub.bz.it/",
    "lastUpdate": "2021-03-10T13:09:12.1985011+01:00"
  },
  "links": {
    "self": "http://example.com/2021-04/agents/bc59f5dd810efdceb1fc673567d02a2f_copyrightOwner"
  },
  "attributes": {
    "abstract": null,
    "description": null,
    "name": {
      "deu": "Tourimusverein Lajen",
      "eng": "Tourimusverein Lajen",
      "ita": "Tourimusverein Lajen"
    },
    "shortName": null,
    "url": null,
    "contactPoints": null
  },
  "relationships": {
    "categories": null,
    "multimediaDescriptions": null
  }
}
