=== noi-techpark/odh-alpinebits-destination-data-server/src/schemas/mediaobject.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://www.alpinebits.org/destinationdata/schemas/2022-04/mediaObject",
  "description": "A resource that implements the concept of Media Object defined in the AlpineBitsÂ® DestinationData Ontology.",
  "type": "object",
  "additionalProperties": false,
  "required": ["type"],
  "properties": {
    "id": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/id"
    },
    "type": {
      "const": "mediaObjects"
    },
    "meta": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/meta"
    },
    "links": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/links"
    },
    "attributes": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "abstract": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "author": {
          "type": [ "null", "string" ],
          "minLength": 1
        },
        "contentType": {
          "type": "string",
          "pattern": "^(application|audio|font|example|image|message|model|multipart|text|video)/[a-zA-Z0-9-.+]+$"
        },
        "description": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "duration": {
          "type": [ "null", "integer" ],
          "exclusiveMinimum": 0
        },
        "height": {
          "type": [ "null", "integer" ],
          "exclusiveMinimum": 0
        },
        "license": {
          "type": [ "null", "string" ],
          "minLength": 1
        },
        "name": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "shortName": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "url": {
          "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/url"
        },
        "width": {
          "type": [ "null", "integer" ],
          "exclusiveMinimum": 0
        }
      }
    },
    "relationships": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "categories": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToMany"
            }
          ]
        },
        "licenseHolder": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToOne"
            }
          ]
        }
      }
    }
  }
}

=== noi-techpark/odh-alpinebits-destination-data-server/test/model/odh2destinationdata/sample_multimedia_description_output.json
{
  "type": "mediaObjects",
  "id": "bc59f5dd810efdceb1fc673567d02a2f",
  "meta": {
    "dataProvider": "http://tourism.opendatahub.bz.it/",
    "lastUpdate": "2021-03-10T13:09:12.1985011+01:00"
  },
  "links": {
    "self": "http://example.com/2021-04/mediaObjects/bc59f5dd810efdceb1fc673567d02a2f"
  },
  "attributes": {
    "abstract": null,
    "description": {
      "deu": "Albions",
      "eng": "Albions",
      "ita": "Albions"
    },
    "name": {
      "deu": "95BEE3DCCD31B7F02E43FE9FB527D244",
      "eng": "95BEE3DCCD31B7F02E43FE9FB527D244",
      "ita": "95BEE3DCCD31B7F02E43FE9FB527D244"
    },
    "shortName": null,
    "url": "https://doc.lts.it/docsite/ImageRender.aspx?ID=bc59f5dd810efdceb1fc673567d02a2f",
    "contentType": "image/jpeg",
    "duration": null,
    "height": 767,
    "license": "CC0-1.0",
    "width": 1023
  },
  "relationships": {
    "categories": null,
    "licenseHolder": {
      "data": {
        "type": "agents",
        "id": "bc59f5dd810efdceb1fc673567d02a2f_licenseHolder"
      },
      "links": {
        "related": "http://example.com/2021-04/mediaObjects/bc59f5dd810efdceb1fc673567d02a2f/licenseHolder"
      }
    }
  }
}
