=== noi-techpark/odh-alpinebits-destination-data-server/src/schemas/skislope.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://www.alpinebits.org/destinationdata/schemas/2022-04/skiSlope",
  "description": "A resource that implements the concept of Ski Slope defined in the AlpineBitsÂ® DestinationData Ontology.",
  "type": "object",
  "additionalProperties": false,
  "required": ["type"],
  "properties": {
    "id": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/id"
    },
    "type": {
      "const": "skiSlopes"
    },
    "meta": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/meta"
    },
    "links": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/links"
    },
    "attributes": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "abstract": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "address": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/address"
            }
          ]
        },
        "description": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "difficulty": {
          "type": [ "null", "object" ],
          "additionalProperties": false,
          "required": ["eu", "us"],
          "properties": {
            "eu": {
              "type":["null", "string"],
              "enum": [null,"novice", "beginner", "intermediate", "expert"]
            },
            "us": {
              "type":["null", "string"],
              "enum": [null,"beginner", "beginner-intermediate", "intermediate", "intermediate-advanced", "expert"]
            }
          },
          "anyOf": [
            {
              "properties": {
                "eu": {
                  "not": {
                    "type": "null"
                  }
                }
              }
            },
            {
              "properties": {
                "us": {
                  "not": {
                    "type": "null"
                  }
                }
              }
            }
          ]
        },
        "geometries": {
          "type": [ "null", "array" ],
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/geometry"
          }
        },
        "howToArrive": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "length": {
          "type": [ "null", "number" ],
          "exclusiveMinimum": 0
        },
        "maxAltitude": {
          "type": [ "null", "number" ]
        },
        "minAltitude": {
          "type": [ "null", "number" ]
        },
        "name": {
          "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
        },
        "openingHours": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/hoursSpecification"
            }
          ]
        },
        "shortName": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "snowCondition": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/snowCondition"
            }
          ]
        },
        "url": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/complexUrl"
            }
          ]
        }
      }
    },
    "relationships": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "categories": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToMany"
            }
          ]
        },
        "connections": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToMany"
            }
          ]
        },
        "multimediaDescriptions": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToMany"
            }
          ]
        }
      }
    }
  }
}

=== noi-techpark/odh-alpinebits-destination-data-server/test/model/odh2destinationdata/sample_ski_slope_activity_output.json
{
  "type": "skiSlopes",
  "id": "4DA19B2B1328127FC062FB79F6F435A5",
  "meta": {
    "dataProvider": "http://tourism.opendatahub.bz.it/",
    "lastUpdate": "2021-03-10T14:16:30.0070278+01:00"
  },
  "links": {
    "self": "http://example.com/2021-04/skiSlopes/4DA19B2B1328127FC062FB79F6F435A5"
  },
  "attributes": {
    "abstract": null,
    "description": {
      "deu": "Diese Rundloipe beim vereisten Dürrensee mit dem fabelhaftem Blick auf die beeindruckenden Drei Zinnen lässt jedes Langläuferherz höher schlagen.",
      "eng": "This loop trail near the icy Dürrensee/Landro lake, with the fabulous view of the imposing Three Peaks, is every cross-country skier’s dream come true.",
      "ita": "Il circuito accanto al Lago di Landro ghiacciato e la vista spettacolare sulle impressionanti Tre Cime di Lavaredo, lascia battere più veloce il cuore di ogni fondista."
    },
    "name": {
      "deu": "11 Toblach: Rundschleife Drei-Zinnen-Blick/Landro",
      "eng": "11 Toblach/Dobbiaco: Round View of the Three Peaks/Landro",
      "ita": "11 Dobbiaco: Annello Vista Tre Cime/Landro"
    },
    "shortName": null,
    "url": {
      "deu": "http://www.toblach.info",
      "eng": "http://www.toblach.info",
      "ita": "http://www.toblach.info"
    },
    "address": {
      "street": {
        "deu": "Dolomitenstraße 3 ",
        "eng": "Dolomitenstr./Via Dolomiti 3",
        "ita": "Via Dolomiti 3"
      },
      "city": {
        "deu": "Toblach",
        "eng": "Toblach/Dobbiaco",
        "ita": "Dobbiaco"
      },
      "region": null,
      "country": "IT",
      "complement": null,
      "categories": null,
      "zipcode": "39034"
    },
    "difficulty": {
      "eu": "beginner",
      "us": null
    },
    "geometries": [
      {
        "type": "Point",
        "coordinates": [12.232614, 46.644231, 1396]
      }
    ],
    "howToArrive": {
      "deu": "Wie Sie Toblach erreichen: https://www.drei-zinnen.info/de/toblach/toblach/kontakt-service/anreise-mobilitaet.htmlVon Toblach in Richtung Süden bis zum Drei-Zinnen-Blick/Landro.",
      "eng": "How to reach Toblach/Dobbiaco: https://www.drei-zinnen.info/en/dobbiaco/dobbiaco/contact-and-service/arrival-mobility.htmlFrom Toblach in southern direction until the View of the Three Peaks/Landro.",
      "ita": "Come arrivare a Dobbiaco: https://www.tre-cime.info/it/dobbiaco/dobbiaco/contatto-servizi/arrivo-mobilita.htmlDa Dobbiaco in direzione sud fino alla Vista Tre Cime/Landro."
    },
    "length": 2800,
    "maxAltitude": 1396,
    "minAltitude": 1420,
    "openingHours": null,
    "snowCondition": null
  },
  "relationships": {
    "categories": {
      "data": [
        {
          "id": "odh:Loipen",
          "type": "categories"
        },
        {
          "id": "alpinebits:cross-country",
          "type": "categories"
        },
        {
          "id": "odh:Klassisch",
          "type": "categories"
        }
      ],
      "links": {
        "related":"http://example.com/2021-04/skiSlopes/4DA19B2B1328127FC062FB79F6F435A5/categories"
      }
    },
    "multimediaDescriptions": null,
    "connections": null
  }
}
