=== noi-techpark/odh-alpinebits-destination-data-server/src/schemas/venue.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://www.alpinebits.org/destinationdata/schemas/2022-04/venue",
  "description": "A resource that implements the concept of Venue defined in the AlpineBitsÂ® DestinationData Ontology.",
  "type": "object",
  "additionalProperties": false,
  "required": ["type"],
  "properties": {
    "id": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/id"
    },
    "type": {
      "const": "venues"
    },
    "meta": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/meta"
    },
    "links": {
      "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/links"
    },
    "attributes": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "abstract": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "address": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/address"
            }
          ]
        },
        "description": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "geometries": {
          "type": [ "null", "array" ],
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/geometry"
          }
        },
        "howToArrive": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "name": {
          "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
        },
        "shortName": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/text"
            }
          ]
        },
        "url": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/complexUrl"
            }
          ]
        }
      }
    },
    "relationships": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "categories": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToMany"
            }
          ]
        },
        "multimediaDescriptions": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "/destinationdata/schemas/2022-04/datatypes#/definitions/relationshipToMany"
            }
          ]
        }
      }
    }
  }
}

=== noi-techpark/odh-alpinebits-destination-data-server/test/model/odh2destinationdata/sample_venue_output.json
{
  "type": "venues",
  "id": "CDB3CC1EE2614488A451C467BE971571_venue",
  "meta": {
    "dataProvider": "http://tourism.opendatahub.bz.it/",
    "lastUpdate": "2019-11-05T00:05:58.776531+01:00"
  },
  "links": {
    "self": "http://example.com/2021-04/venues/CDB3CC1EE2614488A451C467BE971571_venue"
  },
  "attributes": {
    "abstract": null,
    "description": null,
    "name": {
      "deu": "Hotel Taubers Unterwirt",
      "eng": "Hotel Taubers Unterwirt",
      "ita": "Hotel Taubers Unterwirt"
    },
    "shortName": null,
    "url": null,
    "address": {
      "street": null,
      "city": {
        "deu": "Feldthurns",
        "eng": "Velturno",
        "ita": "Vellturno"
      },
      "region": null,
      "complement": null,
      "categories": null,
      "zipcode": null
    },
    "howToArrive": null,
    "geometries": [
      {
        "type": "Point",
        "coordinates": [
          11.5985,
          46.6682
        ]
      }
    ]
  },
  "relationships": {
    "categories": null,
    "multimediaDescriptions": null
  }
}
